- name: local nginx install
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: nginx install
    dnf:
     name: nginx
     state: present

  - name: nginx start
    service:
     name: nginx
     state: started
     enabled: yes

