- name: vars calling from inventory file
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
     msg: " course name: {{ course }}, duration is: {{ duration }}"