- name: print condtion based on condition
  hosts: local
  connection: local
  vars:
   number: 5
  tasks:
  - name: condition check
    ansible.builtin.debug:
     msg: "given number {{ number }} is les  than 10"
    when: number < 10 