- name: installation loop
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: installation loop
     package:
      name: " {{ item }} "
      state: latest
     loop:
     - nginx
     - zip 

