- name: string convert to lower
  hosts: local
  connection: local
  vars:
   stu_name: "JOHN IS BOSS"
  tasks:
  - name: string convertion
    ansible.builtin.debug:
     msg: "string converted to lower case: {{ stu_name | lower }}"