- name: Deploy Apache Tomcat on Ubuntu for your java web applications
  hosts: local
  connection: local
  # gather_facts: yes
  become: yes
  # vars:
  #  tomcat_archive_url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.47/bin/apache-tomcat-10.1.47.tar.gz
  tasks:
    - name: Installing OpenJDK 17 to the host(s)
      ansible.builtin.package:
        name: java-17-openjdk
        update_cache: yes
        state: present

    - name: Deleting content & directory
      ansible.builtin.file:
        state: absent
        path: /opt/tomcat

    - name: Creating /opt/tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        mode: 0755
   
    - name: download tomcat from web
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.47/bin/apache-tomcat-10.1.47.tar.gz
        dest: /tmp/tomcat.tar.gz

    - name: unarchiving
      ansible.builtin.unarchive:
        src: /tmp/tomcat.zip
        dest: /opt/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Adding tomcat group
      ansible.builtin.group:
       name: tomcat
       state: present

    - name: adding user to group
      ansible.builtin.user:
       name: tomcat
       comment: adding tomcat user to tomcat group
       group: tomcat
       home: /opt/tomcat
       shell: /bin/bash

    - name: Changing ownership
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: '0755'
        recurse: yes
        state: directory

    - name: Ensure scripts are executable
      ansible.builtin.file:
      path: /opt/tomcat/bin
      recurse: yes
      mode: '0755'   

    - name: Copying Tomcat service file from local to remote
      ansible.builtin.copy:
       src: tomcat.service
       dest: /etc/systemd/system/tomcat.service
       owner: root
       group: root
       mode: '0644'

    - name: Starting and enabling Tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
        enabled: true
        daemon_reload: true